name: Build Luau - Windows

on:
  workflow_call:
  workflow_dispatch:


jobs:
  build:
    name: Build ${{ matrix.target }} on Windows
    runs-on: windows-latest
    continue-on-error: true
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-gnu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Set up MinGW
        id: mingw_setup
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
          version: 12.2.0

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Build luau-ffi
        working-directory: native/luau-ffi
        env:
          CARGO_BUILD_TARGET: ${{ matrix.target }}
          CC: ${{ steps.mingw_setup.outputs.gcc }}
          CXX: ${{ steps.mingw_setup.outputs.gxx }}
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: luau-ffi-${{ matrix.target }}
          path: |
            native/luau-ffi/target/${{ matrix.target }}/release/libluau.*
